### ISSUE TITLE
Forced refresh causes character set to mess up if language is heb?

### ISSUE THREAD

**Issue by jonorthwash** [goavki/apertium-html-tools#48] opened 2016-01-30 09:03 UTC
![screenshot_2016-01-30_035929](https://cloud.githubusercontent.com/assets/963849/12694786/41f90010-c706-11e5-9c7e-67bc1e530e86.png)

Steps to reproduce issue:
1. Open http://turkic.apertium.org
2. Set page language to Hebrew
3. Shift-ctl-r (or force page reload)

Note that a bunch of non-RTL text becomes RTL.

I've tested this in multiple browsers, and in fresh-cache modes, and the behaviour appears to be consistent.

**Comment by sushain97** [comment] 2016-01-30 19:34
Can reproduce. Absolutely no idea what's going on...

**Comment by sushain97** [comment] 2016-01-30 19:38
Nevermind. This doesn't require hard-refresh or anything. Just switching to heb and refreshing will do the job and it's due to the HTML being transmitted with the wrong encoding: "Content-Type:text/html; charset=iso-8859-8". Should be fixed through Apache settings.

**Comment by jonorthwash** [comment] 2016-01-31 01:08
I set `AddDefaultCharset utf-8` in `charset.conf`, but the behaviour remains unchanged.  Or is this not the right thing to be changed?

Imho, if something as big as this needs to be set in apache, we need to include it in the docs.

**Comment by sushain97** [comment] 2016-12-18 23:18
I don't think that's the right thing to fix. I still get `Content-Type:text/html; charset=iso-8859-8`. Can you add to the `.htaccess` or `httpd.conf`?

**Comment by jonorthwash** [comment] 2016-12-19 00:03
Okay, I put `AddDefaultCharset utf-8` in `.htaccess` in the html-tools directory.

**Comment by sushain97** [comment] 2016-12-19 00:07
This still hasn't fixed it... I'm quite confused since this isn't an issue on apertium.org :(

**Comment by jonorthwash** [comment] 2016-12-19 00:19
Huh...  I can add it to `httpd.conf` and see what happens.

**Comment by Androbin** [comment] 2017-12-27 00:58
Any updates on this yet?

**Comment by jonorthwash** [comment] 2017-12-27 19:27
Still seems to be a problem, even with the line in `/etc/apache2/conf-enabled/charset.conf`.

**Comment by sushain97** [comment] 2018-01-01 20:15
![image](https://user-images.githubusercontent.com/4211838/34470756-225e977a-eefe-11e7-8f8d-5f66372398c0.png)

Did you ever add it to `httpd.conf` and restart Apache?

https://stackoverflow.com/a/913885/1266600

**Comment by TinoDidriksen** [comment] 2018-01-02 06:55
It has to do with Apache's MIME module and `/etc/apache2/mods-available/mime.conf`, specifically the line `AddCharset ISO-8859-8  .iso8859-8  .heb .hebrew`.

One can safely comment out all the `AddLanguage` and `AddCharset` from mime.conf.

**Comment by jonorthwash** [comment] 2018-01-04 07:04
That seems to've worked; thanks @TinoDidriksen!

Yet another reminder of wrong assumption regarding the world being finished moving to UTF-8 and us being done with all the MIME business.  It's funny, Apache's MIME module is probably for backwards-compatibility—maybe they should turn it off by default?

**Closed** 2018-01-04 07:15 UTC
Labels: invalid
