### ISSUE TITLE
Webpage scrollbar to the left for 'rtl' languages webpages

### ISSUE THREAD

**Issue by share-with-me** [goavki/apertium-html-tools#133] opened 2017-05-20 06:52 UTC
The webpage scrollbar for the `rtl` based languages appears on the right. To maintain the semantic consistency of flipping, it should appear at the left.

[Here](https://drive.google.com/open?id=0BwrSYlOsMCyWX1ZsV2VYcmhhdDA) is the demo explaining the issue and also an attempt to achieve the functionality.

**Comment by share-with-me** [comment] 2017-05-20 06:54
Refactored patch I would create. Works well on Firefox and Chrome. Does not reflect in Safari.

**Comment by sushain97** [comment] 2017-05-20 15:40
Duplicate of #127. Let's continue the discussion there.

**Comment by sushain97** [comment] 2017-05-20 15:42
@jonorthwash is this how you would expect it to work?

**Comment by sushain97** [comment] 2017-05-20 15:42
@share-with-me is this only the global scrollbar or all scrollbars?

**Comment by share-with-me** [comment] 2017-05-20 15:52
@sushain97 Only for the global scrollbars! The `textarea` divs already have this behaviour of scrollbar being on the left in case of `rtl` based languages!

**Comment by sushain97** [comment] 2017-05-20 15:54
Why doesn't it already work correctly for the whole page? I think `dir="rtl"`/`dir="ltr"' is being set on the `html/body`?

**Comment by share-with-me** [comment] 2017-05-20 16:15
It seems not all browsers and / or OS support the global scrollbar appearing on the left side by default and even when we override them with `dir="rtl"`. Here is a [stackoverflow link](http://stackoverflow.com/questions/16298320/how-to-change-scrollbar-direction-from-right-to-left) discussing this. A lot of other web resources stated similar. Thus, my approach was to wrap the `body` element inside a `div` and apply the necessary CSS to achieve the scrollbar on the left. 
One more [link](https://bugzilla.mozilla.org/show_bug.cgi?id=1132108) discussing the issue.

**Comment by sushain97** [comment] 2017-05-21 04:07
Ah, thanks for the links.

@jonorthwash can you take a look at them? I'm not convinced that we should divert from the browser default since users will likely be familiar with how their own browser behaves by default.

**Comment by share-with-me** [comment] 2017-05-21 04:21
@sushain97 @jonorthwash Here's a [stackoverflow link](http://stackoverflow.com/questions/1261869/setting-the-correct-orientation-for-scrollbars-in-right-to-left-pages) where users have suggested that it is indeed better to leave the browser settings to the users. Some comments also state that even in rtl based webpages, people (the users) find it annoying to have the scrollbar on the left :P. 

>  I'm not convinced that we should divert from the browser default since users will likely be familiar with how their own browser behaves by default.

If this is the case, I believe I am convinced with the point. Waiting for inputs.

**Comment by jonorthwash** [comment] 2017-05-25 18:35
Hmm yeah I think it's better to use the browser default.  If some browsers can put the scrollbar on the other side, then we should specify that they do so, but otherwise we shouldn't force a behaviour on people who are used to their browser doing something else.  That is, we should leave it up to the browser—maybe it's a config option in some.

**Closed** 2017-05-25 18:41 UTC
Labels: wontfix

**Comment by share-with-me** [comment] 2017-05-25 18:42
>  If some browsers can put the scrollbar on the other side, then we should specify that they do so, but otherwise we shouldn't force a behaviour on people who are used to their browser doing something else.

Very much convinced @jonorthwash . If people are used to having a specific setting by default in their browser, we shouldn't force it.
