### ISSUE TITLE
"suggest a better translation"

### ISSUE THREAD

**Issue by unhammer** [goavki/apertium-html-tools#10] opened 2015-02-12 07:44 UTC
We really should have a way for users to 
- tell us when a particular translation is bad / could be better
- and also to give longer word lists

I'm not sure if this can be just one box that's expandable or what the best UI would be.

**Comment by sushain97** [comment] 2016-12-18 23:41
Duplicate of #55 (yes this one came first but the other has more info :)

**Closed by sushain97** 2016-12-18 23:41 UTC
Labels: enhancement
