### ISSUE TITLE
Download translated documents on iOS

### ISSUE THREAD

**Issue by sabakkps** [goavki/apertium-html-tools#231] opened 2017-12-19 15:39 UTC
Hi guys!
I am unable to download any translated document on iOS 11 on iPhone 6.
Please help!

**Comment by omairqazi** [comment] 2017-12-19 15:41
Well, Apple rules don't allow this. But you can try downloading a download manager in App Store and try using it.

**Comment by sushain97** [comment] 2017-12-19 15:49
Duplicate of #222.

**Closed by sushain97** 2017-12-19 15:49 UTC
